name: Build HW75 Keyboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -f requirements.txt; fi
          
      - name: Build keyboard firmware
        run: |
          # Add your build commands here
          # For example:
          # make hw75_keyboard:default
          
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: hw75_keyboard-firmware
          path: |
            # Specify your firmware output path
            # For example:
            # .build/hw75_keyboard_default.hex
            # .build/hw75_keyboard_default.bin
